<?php

namespace BoldMinded\Speedy\Service\Drivers;

use ExpressionEngine\Library\Filesystem\Filesystem;
use BoldMinded\Speedy\Service\CacheItem;
use BoldMinded\Speedy\Service\Drivers\Configuration\StaticSettingsForm;
use BoldMinded\Speedy\Service\Drivers\Support\SupportValidator;

class StaticDriver extends AbstractFilesystemDriver implements ConfigurableDriverInterface
{
    const NAME = 'static';

    /** @var array */
    private $settings = [];

    /** @var bool */
    private $hasFileConfigOverride = false;

    public function __construct()
    {
        // Highly recommended if using Queue to break and refresh cache
        if (ee()->config->item('speedy_static_path') !== false) {
            $cachePath = rtrim(ee()->config->item('speedy_static_path'), '/');
        }

        if (empty($cachePath)) {
            $cachePath = rtrim($this->getDocumentRootPath(), '/') . '/static';
        }

        parent::__construct($cachePath);
    }

    public function configure(array $settings): void
    {
        $this->settings = $settings;
    }

    /**
     * @param string $contents
     * @param array  $headers
     * @param int    $createdAt
     * @param int    $expiresAt
     * @param string $filePath
     * @return string
     */
    private function buildStaticFileContents(
        string $contents,
        array $headers,
        int $createdAt,
        int $expiresAt,
        string $filePath,
        string $filePathHtml
    ): string {
        $class = 'Speedy_' . hash('md5', uniqid('', true));
        $contents = $this->buildStaticFileContentsValue($contents);
        $headers = $this->buildStaticFileHeadersValue($headers);
        $indexFile = defined('EESELF') ? EESELF : SELF; // SELF is deprecated
        $indexPath = FCPATH;
        $allowList = ee()->config->item('speedy_query_cache_allowlist') ?: [];
        $allowList = var_export($allowList, true);
        $staticUtilitiesPath = $this->cachePath . '/utilities';
        $options = var_export([
            // Set a few path vars based off constants since we won't be booting EE.
            'appPath' => APPPATH,
            'basePath' => BASEPATH,
            // Prefix check borrowed from core.
            'cookiePrefix' => (!ee()->config->item('cookie_prefix')) ? 'exp_' : ee()->config->item('cookie_prefix') . '_',
            'configPath' => SYSPATH . 'user/config/config.php' ,
            'databasePrefix' => ee()->db->dbprefix,
            'frontEditCheckUrl' => ee()->config->item('speedy_frontedit_check_url') ?? '',
            'systemPath' => SYSPATH,
        ], true);

        // @todo Could be a useful place for a hook to write different cache file

        return <<<EOF
<?php

/** * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *          WARNING: This file is automatically generated!          *
 *            Any changes made to this file will be lost            *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * **/

if (!class_exists('{$class}')) {
    if (!defined('SPEEDY_STATIC_START')) {
        define('SPEEDY_STATIC_START', microtime(true));
    }
    if (!class_exists('StaticCacheHelper')) {
        require_once '{$staticUtilitiesPath}/StaticCacheHelper.php';
    }
    if (!class_exists('SpeedyCsrf')) {
        require_once '{$staticUtilitiesPath}/Csrf/SpeedyCsrfStorageInterface.php';
        require_once '{$staticUtilitiesPath}/Csrf/SpeedyCookie.php';
        require_once '{$staticUtilitiesPath}/Csrf/SpeedyDatabase.php';
        require_once '{$staticUtilitiesPath}/Csrf/SpeedyCsrf.php';
    }

    class {$class} {
        public \$contents = '{$contents}';
        public \$createdAt = {$createdAt};
        public \$expiresAt = {$expiresAt};
        private \$filePath = '{$filePath}';
        private \$filePathHtml = '{$filePathHtml}';
        private \$queryStringFilePath = '';
        private \$staticCacheHelper = null;

        public function __construct()
        {
            \$csrf = new SpeedyCsrf({$options});
            \$csrf->checkToken();
            \$csrf->setTokenHeader();

            \$this->staticCacheHelper = new StaticCacheHelper({$allowList}, \$_GET, \$csrf, {$options});
            \$queryString = \$this->staticCacheHelper->getQueryStringEncoded();
            \$delim = StaticCacheHelper::QUERY_DELIMITER;

            if (\$queryString && strpos(\$this->filePath, \$delim . \$queryString . '/index.php') === false) {
                \$this->queryStringFilePath = str_replace('/index.php', \$delim . \$queryString . '/index.php', \$this->filePath);
            }
        }

        public function output()
        {
            if (\$this->isExpired()) {
                \$this->redirect();
            } else if (\$this->staticCacheHelper->isFrontEditEnabled()) {
                \$this->redirect(false);
            } else if (isset(\$_GET['speedy_bypass'])) {
                \$this->redirect();
            } else {
                \$this->handleQueryString();
                \$this->render();
            }
        }

        public function isExpired()
        {
            return \$this->expiresAt !== 0 && \$this->expiresAt <= time();
        }

        private function isSelf()
        {
            return \$this->queryStringFilePath === \$this->filePath;
        }

        private function handleQueryString()
        {
            if (file_exists(\$this->queryStringFilePath)) {
                require_once \$this->queryStringFilePath;
                exit;
            }

            if (!\$this->isSelf() && \$this->queryStringFilePath) {
                \$this->redirect(false);
                exit;
            }
        }

        private function render()
        {
            {$headers}

            if (file_exists(\$this->filePathHtml)) {
                echo \$this->staticCacheHelper->prepareHtmlContent(file_get_contents(\$this->filePathHtml));
                exit;
            }

            echo \$this->staticCacheHelper->prepareContent(\$this->contents);
            exit;
        }

        private function redirect(\$deleteSelf = true)
        {
            if (\$deleteSelf) {
                @unlink(__FILE__);
            }

            global \$CI;
            chdir('{$indexPath}');
            require '{$indexPath}{$indexFile}';
        }
    }
}

if (!defined('SPEEDY_NAME')) {
    \$cache = new {$class}();
    \$cache->output();
}

return new {$class}();
EOF;
    }

    private function buildStaticFileContentsValue(string $contents): string
    {
        return str_replace(['"', "'", "\n"], ['\\"', "\'", '\n'], $contents);
    }

    private function buildStaticFileHeadersValue(array $headers): string
    {
        $return = '';
        foreach ($headers as $header => $value) {
            $return .= "header('{$header}: {$value}');\n            ";
        }

        return trim($return);
    }

    /**
     * @param string $key
     * @return bool
     */
    protected function checkIgnoreUrls(string $key): bool
    {
        if (!isset($this->settings['ignore_urls']) || empty($this->settings['ignore_urls'])) {
            return false;
        }

        $key = preg_replace('#^static/#', '', $key);

        foreach ($this->settings['ignore_urls'] as $setting) {
            if (preg_match('#' . $setting['url'] . '#', $key)) {
                return true;
            }
        }

        return false;
    }

    public function countItems(): int
    {
        $count = iterator_count($this->getIterator());

        if (ee()->config->item('speedy_static_use_html_file') === 'yes') {
            return $count / 2; // Each item has both .php and .html files.
        }

        return $count;
    }

    /**
     * @return array
     */
    private function collectOutputHeaders(): array
    {
        $headers = [];

        if (isset(ee()->output->headers) && is_array(ee()->output->headers)) {
            foreach (ee()->output->headers as $header) {
                if (isset($header[0]) && preg_match('~^([^:]+):\s*(.+)$~', $header[0], $matches)) {
                    $headers[$matches[1]] = $matches[2];
                }
            }
        }

        return $headers;
    }

    public function doFetch(string $key): string
    {
        $now = time();
        $file = $this->getFilename($key);

        $this->getLogger()->debug(sprintf('Reading data file name "%s".', $file));

        if (!file_exists($file)) {
            $this->getLogger()->info('Cache file does not exist.');
            throw new ItemNotFoundException();
        }

        try {
            $cache = require $file;
        } catch (\Exception $exception) {
            $this->getLogger()->info(sprintf('Can\'t load %s: %s', $file, $exception->getMessage()));

            throw new ItemNotFoundException();
        }

        if ($cache->isExpired()) {
            $this->getLogger()->info('Cache file has expired.', [
                'expires_at'   => $cache->expiresAt,
                'current_time' => $now,
            ]);

            throw new ItemNotFoundException();
        }

        $this->getLogger()->debug('Reading cache file data.');

        return $cache->contents;
    }

    public function doSave(string $key, string $value, int $ttl): bool
    {
        if ($this->checkIgnoreUrls($key) || $this->isFrontEdit($value)) {
            return $value;
        }

        $createdAt = $this->getCreatedAt();

        if ($ttl === false || (is_numeric($ttl) && (int) $ttl === 0)) {
            $expiresAt = 0;
        } else {
            // Prevent redirect loops caused by short ttl.
            if ($ttl < 5) {
                $ttl = 5;
            }

            $expiresAt = $createdAt + $ttl;
        }

        // Collect output headers so we can send them when the cache is hit.
        $headers = array_merge(
            $this->collectOutputHeaders(),
            $this->buildCacheHeaders(
                $createdAt,
                $expiresAt,
                $this->settings['purger'] ?? null
            )
        );

        $filePath = $this->getFilename($key);
        $filePathHtml = $this->getHtmlFilename($key);

        $data = $this->buildStaticFileContents($value, $headers, $createdAt, $expiresAt, $filePath, $filePathHtml);

        $this->getLogger()->debug(sprintf('Writing data file name "%s".', $filePath));

        // If enabled, this will create an index.html file alongside the index.php file,
        // and the php file will load the contents of the .html file instead of the value
        // in the $contents property of the php file. It might be worth defaulting to this
        // in a future release to avoid any rare edge cases where the HTML isn't encoded properly.
        // https://boldminded.com/support/ticket/3118
        if (ee()->config->item('speedy_static_use_html_file') === 'yes') {
            $this->writeFile($filePathHtml, $value);
        }

        // The php file is still necessary to manage redirects, writing out expires headers etc.
        return $this->writeFile($filePath, $data, $expiresAt);
    }

    public function deletePath(string $path): bool
    {
        $file = $this->getFilename($path, false);

        return $this->clearCachePath($file);
    }

    public function deleteItem(string $key): bool
    {
        if (CacheItem::isKeyRegex($key)) {
            return parent::deleteMatchingItems($key . '/index.php');
        }

        return parent::deleteItem($key);
    }

    public function getConfigurationForm(): StaticSettingsForm
    {
        return new StaticSettingsForm();
    }

    public function getConfiguredValidator(): SupportValidator
    {
        return SupportValidator::create();
    }

    public function getSupportValidator(): SupportValidator
    {
        return SupportValidator::create()
            ->addRule('Static cache is enabled.', function () {
                //  Make sure $config['speedy_static_enabled'] = 'yes'; is in your config.php file
                return ee()->config->item('speedy_static_enabled') === 'yes';
            })
            ->addRule('Cache path is set', function () {
                return $this->cachePath !== '';
            })
            ->addRule('Cache path is writable', function () {
                return (new Filesystem())->isWritable($this->cachePath);
            });
    }

    public function getItemMetadata(string $key): array
    {
        $file = $this->getFilename($key);

        if (!file_exists($file)) {
            throw new ItemNotFoundException();
        }

        $cache = require $file;

        $fileSize = filesize($file);
        $createdAt = $cache->createdAt;
        $expiresAt = $cache->expiresAt;

        return [
            self::META_TTL           => $expiresAt > 0 ? ($expiresAt - $createdAt) : 0,
            self::META_TTL_REMAINING => $expiresAt > 0 ? ($expiresAt - time()) : 0,
            self::META_SIZE          => $fileSize,
            self::META_CREATED_AT    => $createdAt,
            self::META_EXPIRES_AT    => $expiresAt,
        ];
    }

    public function getName(): string
    {
        return self::NAME;
    }

    public function getStats(): array
    {
        $usage = 0;
        foreach ($this->getIterator() as $name => $file) {
            $usage += $file->getSize();
        }

        $available = disk_free_space($this->cachePath);

        return [
            self::STATS_HITS             => null,
            self::STATS_MISSES           => null,
            self::STATS_UPTIME           => null,
            self::STATS_MEMORY_USAGE     => $usage,
            self::STATS_MEMORY_AVAILABLE => $available,
        ];
    }

    protected function getFilename(string $key, bool $validateKey = true): string
    {
        CacheItem::validateKey($key);

        // Ensure the key ends with 'index.php'
        if ($validateKey && !preg_match('~/index.php$~', $key)) {
            $key = rtrim($key, '/') . '/index.php';
        }

        return parent::getFilename($key);
    }

    protected function getHtmlFilename(string $key, bool $validateKey = true): string
    {
        CacheItem::validateKey($key);

        // Ensure the key ends with 'index.html'
        if ($validateKey && !preg_match('~/index.html$~', $key)) {
            $key = rtrim($key, '/') . '/index.html';
        }

        return parent::getFilename($key);
    }

    protected function formatItemPathName(string $name): string
    {
        $suffix = strlen('/index.php');

        return substr($name, 0, -1 * $suffix);
    }

    public function hasFileConfigOverride(): bool
    {
        return $this->hasFileConfigOverride;
    }

    /**
     * @param bool $hasFileConfigOverride
     */
    public function setHasFileConfigOverride(bool $hasFileConfigOverride): StaticDriver
    {
        $this->hasFileConfigOverride = $hasFileConfigOverride;

        return $this;
    }
}
